version: '3.8'  # Docker Compose file version

services:
  db:
    image: mariadb:lts-noble
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MY_MARIADB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - docker_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.role == db  # VM1에 배포
  kafka:
    image: bitnami/kafka:3.9.0
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_HEAP_OPTS="-Xmx512M -Xms512M"
      - KAFKA_CFG_NUM_PARTITIONS=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_LOG_RETENTION_MS=60000
      - KAFKA_CFG_LOG_RETENTION_BYTES=20971520
      - KAFKA_CFG_LOG_SEGMENT_BYTES=10485760
      - KAFKA_CFG_LOG_FLUSH_INTERVAL_MS=5000
      - KAFKA_CFG_LOG_FLUSH_INTERVAL_MESSAGES=10000
      - KAFKA_CFG_LOG_CLEANUP_POLICY=delete
      - KAFKA_CFG_COMPRESSION_TYPE=snappy
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - docker_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.role == kafka  # VM1에 배포
  api:
    image: 10.0.1.251:5000/kimpscan:0.0.1
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    networks:
      - docker_net
#    command: ["tail", "-f", "/dev/null"]
    deploy:
      replicas: 1  # Swarm 모드에서 서비스의 복제본 수를 설정 (여기서는 1개로 설정)
      restart_policy:
        condition: on-failure  # 실패 시 재시작 정책
      placement:
        constraints:
          - node.labels.role == service  # VM1에 배포

networks:
  docker_net:
    driver: overlay

volumes:
  db_data:
    driver: local
  kafka_data:
    driver: local
  registry_data:
    driver: local
