# Step 1: Build React app
FROM node:22-alpine3.20 AS builder

WORKDIR /app

COPY ./kimpscan-web/package*.json ./
RUN npm install

COPY ./kimpscan-web .
COPY ./icons ./public/icons
RUN npm run build

# Step 2: Nginx to serve the build
FROM nginx:1.26.3-alpine

# Nginx 설정 파일을 컨테이너에 복사
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

# 빌드된 리액트 파일을 Nginx 웹 루트로 복사
COPY --from=builder /app/dist /usr/share/nginx/html


# 80번 포트 개방
EXPOSE 80

# Nginx 실행
CMD ["nginx", "-g", "daemon off;"]
