# JDK 21을 사용하는 Gradle 8.11.1 이미지를 기반으로 빌드를 진행
FROM amazoncorretto:21-alpine3.20 AS builder

# 작업 디렉토리 설정
WORKDIR /app

# 필요한 소스 파일 복사
COPY ./kimpscan-backend .

# Gradle wrapper 실행 (빌드)

RUN chmod +x gradlew
RUN ./gradlew build --no-daemon

# 최종 이미지로 JDK 21만 사용하여 JAR 파일 실행
FROM amazoncorretto:21-alpine3.20

# 작업 디렉토리 설정
WORKDIR /app

# 빌드된 JAR 파일을 복사
COPY --from=builder /app/build/libs/*.jar /app/spring.jar

# Java 애플리케이션 실행
CMD ["java",  "-Dspring.profiles.active=prod", "-jar", "spring.jar"]
